spring:
  application:
    name: p3-spring-security
  security:
    oauth2:
      client:
        registration:
          github:
            client-id:
            client-secret:

server:
  port: 9090