services:
  eureka-server:
    image: eureka-server
    build:
      context: eureka-server
      dockerfile: Dockerfile

  api-gateway:
    image: api-gateway
    build:
      context: api-gateway
      dockerfile: Dockerfile
    depends_on:
      - eureka-server

  user-service:
    image: user-service
    build:
      context: user-service
      dockerfile: Dockerfile
    depends_on:
      - eureka-server
      - api-gateway

  product-catalog-service:
    image: product-catalog-service
    build:
      context: product-catalog-service/
      dockerfile: Dockerfile
    depends_on:
      - eureka-server
      - api-gateway

  order-processing-service:
    image: order-processing-service
    build:
      context: order-processing-service
      dockerfile: Dockerfile
    depends_on:
      - eureka-server
      - api-gateway
