apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog-service
  labels:
    app: product-catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-catalog-service
  template:
    metadata:
      name: product-catalog-service
      labels:
        app: product-catalog-service
    spec:
      containers:
        - name: product-catalog-service
          image: product-catalog-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8088
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: product-catalog-service
spec:
  selector:
    app: product-catalog-service
  ports:
    - port: 8088
      targetPort: 8088
  type: NodePort
