spring:
  application:
    name: order-processing-service

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        retryer:
          period: 1000
          maxPeriod: 5000
          maxAttempts: 3

user-service:
  url: http://localhost:8081
product-catalog-service:
  url: http://localhost:8082