spring:
  application:
    name: order-processing-service

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        retryer:
          period: 1000
          maxPeriod: 5000
          maxAttempts: 3

user-service:
  url: http://user-service:8081
product-catalog-service:
  url: http://product-catalog-service:8082