spring:
  application:
    name: Lab5
  datasource:
    url: jdbc:postgresql://10.128.138.152:5432/lab5_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  admin:
    name: admin
    email: admin@lab5.com
    password:
  security:
    jwt:
      secret-key: